"""
Report Generator — creates structured HTML pentest reports.
"""

import time
import json
from pathlib import Path
from typing import Optional
from rich.console import Console
from rich.prompt import Prompt, Confirm
from core.utils import REPORTS_DIR, log_event

console = Console()

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DeadDroid Pentest Report — {title}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9; }}
  header {{ background: linear-gradient(135deg,#161b22,#21262d); padding: 40px; border-bottom: 1px solid #30363d; }}
  header h1 {{ color: #ff4444; font-size: 2rem; }}
  header p  {{ color: #8b949e; margin-top: 6px; }}
  .badge {{ display:inline-block; padding:4px 10px; border-radius:12px; font-size:.75rem; font-weight:600; margin-top:10px; }}
  .badge-critical {{ background:#ff000033; color:#ff4444; border:1px solid #ff4444; }}
  .badge-high     {{ background:#ff880033; color:#ff8800; border:1px solid #ff8800; }}
  .badge-medium   {{ background:#ffcc0033; color:#ffcc00; border:1px solid #ffcc00; }}
  .badge-low      {{ background:#00cc6633; color:#00cc66; border:1px solid #00cc66; }}
  .badge-info     {{ background:#0088ff33; color:#0088ff; border:1px solid #0088ff; }}
  main {{ max-width:1100px; margin:40px auto; padding:0 20px; }}
  section {{ background:#161b22; border:1px solid #30363d; border-radius:10px; margin-bottom:24px; padding:28px; }}
  section h2 {{ color:#58a6ff; font-size:1.1rem; margin-bottom:16px; border-bottom:1px solid #30363d; padding-bottom:10px; }}
  table {{ width:100%; border-collapse:collapse; }}
  th {{ background:#21262d; color:#58a6ff; padding:10px; text-align:left; font-weight:600; }}
  td {{ padding:10px; border-top:1px solid #21262d; }}
  code {{ background:#161b22; border:1px solid #30363d; border-radius:4px; padding:2px 6px; font-family:monospace; color:#7ee787; font-size:.85rem; }}
  pre  {{ background:#0d1117; border:1px solid #30363d; border-radius:6px; padding:16px; overflow-x:auto; }}
  pre code {{ background:none; border:none; padding:0; }}
  .finding {{ margin-bottom:20px; padding:18px; background:#0d1117; border-radius:8px; border-left:4px solid #ff4444; }}
  .finding h3 {{ color:#e6edf3; margin-bottom:8px; }}
  footer {{ text-align:center; padding:30px; color:#484f58; font-size:.85rem; }}
  footer a {{ color:#58a6ff; text-decoration:none; }}
</style>
</head>
<body>
<header>
  <h1>&#9760; DeadDroid Pentest Report</h1>
  <p>{title}</p>
  <p style="margin-top:8px;color:#8b949e">Generated: {date} &nbsp;|&nbsp; Tester: {tester} &nbsp;|&nbsp; Target: {target}</p>
</header>
<main>

  <section>
    <h2>Executive Summary</h2>
    <p>{summary}</p>
  </section>

  <section>
    <h2>Scope &amp; Methodology</h2>
    <table>
      <tr><th>Item</th><th>Details</th></tr>
      <tr><td>Target Device / App</td><td>{target}</td></tr>
      <tr><td>Test Type</td><td>{test_type}</td></tr>
      <tr><td>Authorization</td><td>{authorization}</td></tr>
      <tr><td>Start Date</td><td>{start_date}</td></tr>
      <tr><td>End Date</td><td>{end_date}</td></tr>
      <tr><td>Tools Used</td><td>{tools}</td></tr>
    </table>
  </section>

  <section>
    <h2>Findings</h2>
    {findings_html}
  </section>

  <section>
    <h2>Payload Summary</h2>
    {payloads_html}
  </section>

  <section>
    <h2>Recommendations</h2>
    <p>{recommendations}</p>
  </section>

</main>
<footer>
  <p>Generated by <strong>DeadDroid v2.0</strong> &mdash; Android Penetration Testing Framework</p>
  <p>Author: <a href="https://github.com/faizzyhon">faizzyhon</a> &nbsp;|&nbsp;
     <a href="https://faizzyhon.dev">faizzyhon.dev</a> &nbsp;|&nbsp;
     <a href="https://t.me/faizzyhon">Telegram</a></p>
  <p style="margin-top:8px;color:#ff444488">This report is confidential. For authorised use only.</p>
</footer>
</body>
</html>
"""

FINDING_TEMPLATE = """
<div class="finding">
  <span class="badge badge-{severity_lower}">{severity}</span>
  <h3>{title}</h3>
  <p><strong>Description:</strong> {description}</p>
  <p><strong>Impact:</strong> {impact}</p>
  <p><strong>Evidence:</strong></p>
  <pre><code>{evidence}</code></pre>
  <p><strong>Recommendation:</strong> {recommendation}</p>
</div>
"""


def _build_findings_html(findings: list[dict]) -> str:
    if not findings:
        return "<p>No findings recorded.</p>"
    html = ""
    for f in findings:
        html += FINDING_TEMPLATE.format(
            severity_lower=f.get("severity", "info").lower(),
            severity=f.get("severity", "INFO").upper(),
            title=f.get("title", "Untitled"),
            description=f.get("description", ""),
            impact=f.get("impact", ""),
            evidence=f.get("evidence", "").replace("<", "&lt;").replace(">", "&gt;"),
            recommendation=f.get("recommendation", ""),
        )
    return html


def _build_payloads_html(payloads: list[dict]) -> str:
    if not payloads:
        return "<p>No payloads recorded.</p>"
    rows = ""
    for p in payloads:
        rows += f"<tr><td>{p.get('name','')}</td><td><code>{p.get('type','')}</code></td><td>{p.get('lhost','')}:{p.get('lport','')}</td><td>{p.get('notes','')}</td></tr>"
    return f"""
    <table>
      <tr><th>File</th><th>Type</th><th>LHOST:LPORT</th><th>Notes</th></tr>
      {rows}
    </table>"""


def generate_report(
    title: str,
    tester: str,
    target: str,
    summary: str,
    findings: list[dict],
    payloads: list[dict] = None,
    test_type: str = "Black Box",
    authorization: str = "Written authorization obtained",
    start_date: str = "",
    end_date: str = "",
    tools: str = "DeadDroid, Metasploit, apktool, msfvenom",
    recommendations: str = "",
) -> Path:

    payloads = payloads or []
    now      = time.strftime("%Y-%m-%d %H:%M UTC")
    filename = f"report_{title.replace(' ','_')}_{time.strftime('%Y%m%d_%H%M%S')}.html"
    out_path = REPORTS_DIR / filename

    html = HTML_TEMPLATE.format(
        title=title,
        date=now,
        tester=tester,
        target=target,
        summary=summary,
        test_type=test_type,
        authorization=authorization,
        start_date=start_date or now,
        end_date=end_date or now,
        tools=tools,
        findings_html=_build_findings_html(findings),
        payloads_html=_build_payloads_html(payloads),
        recommendations=recommendations,
    )

    out_path.write_text(html, encoding="utf-8")
    log_event(f"Report generated: {out_path}")
    console.print(f"[green]✔ Report saved:[/] {out_path}")
    return out_path


def interactive_report():
    console.rule("[bold cyan]Report Generator[/]")

    title   = Prompt.ask("Report title",    default="Android Penetration Test")
    tester  = Prompt.ask("Tester name",     default="Security Team")
    target  = Prompt.ask("Target (device/app)")
    summary = Prompt.ask("Executive summary")
    recs    = Prompt.ask("Recommendations")

    findings: list[dict] = []
    while Confirm.ask("Add a finding?", default=True):
        f = {
            "title":          Prompt.ask("Finding title"),
            "severity":       Prompt.ask("Severity", choices=["Critical","High","Medium","Low","Info"], default="High"),
            "description":    Prompt.ask("Description"),
            "impact":         Prompt.ask("Impact"),
            "evidence":       Prompt.ask("Evidence / PoC"),
            "recommendation": Prompt.ask("Recommendation"),
        }
        findings.append(f)

    path = generate_report(
        title=title,
        tester=tester,
        target=target,
        summary=summary,
        findings=findings,
        recommendations=recs,
    )
    console.print(f"\n[bold]Open in browser:[/] file://{path.resolve()}")
